/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#291800",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#341100",
        "primary-container": "#1e3a5f",
        "primary-fixed": "#d5e3ff",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#2d486d",
        "tertiary-container": "#503300",
        "secondary-fixed-dim": "#ffb690",
        "on-surface": "#191c1e",
        "on-secondary-container": "#5c2400",
        "surface-container": "#eceef0",
        "tertiary-fixed-dim": "#edbf7f",
        "secondary": "#9d4300",
        "surface-container-highest": "#e0e3e5",
        "on-surface-variant": "#43474e",
        "error-container": "#ffdad6",
        "on-primary-container": "#8aa4cf",
        "primary-fixed-dim": "#adc8f5",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffddb2",
        "tertiary": "#341f00",
        "background": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "outline": "#74777f",
        "on-primary-fixed": "#001c3b",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#fd761a",
        "secondary-fixed": "#ffdbca",
        "on-tertiary-fixed-variant": "#60410c",
        "on-error": "#ffffff",
        "outline-variant": "#c4c6cf",
        "surface-tint": "#455f87",
        "surface-dim": "#d8dadc",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#c69b5f",
        "primary": "#022448",
        "on-secondary-fixed-variant": "#783200",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#adc8f5",
        "surface-bright": "#f7f9fb",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        "soft": "0 2px 32px 0 rgba(25, 28, 30, 0.04)",
        "ambient": "0 8px 32px 0 rgba(25, 28, 30, 0.08)",
      },
    },
  },
  plugins: [],
};
